### ISSUE TITLE
 ERROR: (gcloud.app.deploy) Error Response: [4] Timed out waiting for the flex deployment to become network provisioned.

### ISSUE THREAD

**Issue by zakariandys** [GoogleCloudPlatform/gcloud-maven-plugin#112]
When I deployed my java application to appengine using command `mvn gcloud:deploy` I got error message which indicate that m deployment is failure. There is the message error I got.
`[INFO] ERROR: (gcloud.app.deploy) Error Response: [4] Timed out waiting for the flex deployment to become network provisioned.
[ERROR] Error: gcloud app command with exit code : 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27:33 min
[INFO] Finished at: 2018-03-06T19:16:02+07:00
[INFO] Final Memory: 26M/238M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.appengine:gcloud-maven-plugin:2.0.9.133.v20161104:deploy (default-cli) on project kofera-builder-adwords-worker: Error: gcloud app command exit code is: 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

**Comment by joshnewlinatclearobject** [comment]
Was this ever resolved @zakariandys ?

**Comment by loosebazooka** [comment]
@meltsufin ? Is this a timeout thing on the flex images?

**Comment by meltsufin** [comment]
No, it's more likely the timeout in the Cloud Build or the actual App Engine Flex infrastructure.

**Comment by zakariandys** [comment]
the problem is solved. Main issue on healthchecker, when deployment app engine flex return bad request.

**Comment by JCarlosR** [comment]
@zakariandys How did you solve it? Was it just a matter of time?

**Comment by zakariandys** [comment]
@JCarlosR no, it was my mistake to configure the health checker

**Comment by vishnu4mohan** [comment]
@zakariandys How did you configure health checker? Through liveness check or readiness check in app.yaml?
