### ISSUE TITLE
Maven gcloud:run does not use Dockerfile

### ISSUE THREAD

**Issue by waprin** [GoogleCloudPlatform/gcloud-maven-plugin#48]
Trying to run this project:

https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/java/managed-vm-gae

Results in maven not picking up Dockerfile (builds wrong image), not reading environment variables, etc.

@ludoch

**Comment by ludoch** [comment]
The dockerfile (for now) has to be located at the root of the built War directory.
To achieve this, it has to be in the src area of the Web App, so in 
https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/java/managed-vm-gae/src/main/webapp

**Comment by ludoch** [comment]
See an example of file location at https://github.com/GoogleCloudPlatform/appengine-java-vm-guestbook-extras/tree/master/stage2/src/main/webapp
