### ISSUE TITLE
Plugin Doesn't Properly Stop Old Appservers

### ISSUE THREAD

**Issue by waprin** [GoogleCloudPlatform/gcloud-maven-plugin#49]
Sometimes when I run mvn gcloud:run a few times in a row, the process does not fully exit, and the new process fails to stop the app server and thus hangs right at the beginning of the run stage. I workaround this my manually killing the old process using port 8000.

I will try to get you a more easily reproducible bug for this, just a heads up that I've repeatedly run into it.

**Comment by ludoch** [comment]
Yes, I think it is more a devappserver process bug. I've seen the behavior as well.
