### ISSUE TITLE
support dispatch.yaml files...

### ISSUE THREAD

**Issue by aleemstreak** [GoogleCloudPlatform/gcloud-maven-plugin#5]

**Comment by ludoch** [comment]
Can you describe more what is needed there? We can help, but need data.

**Comment by ludoch** [comment]
If there is a dispatch.xml in WEB-INF,it will be be translated at deploy time to a dispatch.yaml at the root of the staging directory, and will be uploaded in the gcloud:deploy command.
version 0.9.58.v20150503
