### ISSUE TITLE
mvn gcloud:deploy fails for non-vm java app with java6 not supported error

### ISSUE THREAD

**Issue by estrellis** [GoogleCloudPlatform/gcloud-maven-plugin#55]
- gcloud setting app/use_appengine_api set to true
- gcloud plugin version 2.0.9.81.v20151008

web.xml:
<appengine-web-app xmlns="http://appengine.google.com/ns/1.0"><application>egs-test-qa2</application><threadsafe>true</threadsafe><version>pkb-appengine-e8b372bd</version><manual-scaling><instances>1</instances></manual-scaling><instance-class>B4_1G</instance-class></appengine-web-app>  

Diagnostic:
INFO] Details: [
[INFO]   [
[INFO]     {
[INFO]       "@type": "type.googleapis.com/google.rpc.DebugInfo",
[INFO]       "detail": "[ORIGINAL ERROR] generic::invalid_argument: Java 6 applications are prevented from being deployed to Google App Engine from any version of the SDK, including older ones. If you need to continue to deploy Java 6 applications for compatibility reasons, you can request that your application be whitelisted for Java 6 deployment by visiting http://goo.gl/ycffXq. [google.rpc.error_details_ext] { code: 3 message: \"Java 6 applications are prevented from being deployed to Google App Engine from any version of the SDK, including older ones. If you need to continue to deploy Java 6 applications for compatibility reasons, you can request that your application be whitelisted for Java 6 deployment by visiting http://goo.gl/ycffXq.\" }"
[INFO]     }
[INFO]   ]
[INFO] ]

**Comment by ludoch** [comment]
Fix is in the new release I pushed.
<version>2.0.9.83.v20151021</version>
Should be online soon, when Maven central has it.
