### ISSUE TITLE
gcloud:deploy fails due to presence of Dockerfile in /tmp/ staging directory when app.yaml's runtime is "java"

### ISSUE THREAD

**Issue by dt-rush** [GoogleCloudPlatform/gcloud-maven-plugin#62]
Exactly as the title suggests, gcloud:deploy is failing for me because my java app is staged into a subdirectory of /tmp where it has an app.yaml and a Dockerfile generated for it. 

The app.yaml:

    runtime: java7
    vm: True
    module: 'mvnhello'
    inbound_services:
    - warmup
    derived_file_type:
    - java_precompiled
    threadsafe: True
    auto_id_policy: default
    health_check:
      enable_health_check: True
    api_version: '1.0'
    handlers:
    - url: (/.*)
      static_files: __static__\1
      upload: __NOT_USED__
      require_matching_file: True
      login: optional
    ...etc...

The Dockerfile:

    FROM gcr.io/google_appengine/java-compat
    ADD . /app

In this case, it seems generating "runtime: custom" would be more useful in this case, since the Dockerfile already takes care of the runtime by using `gcr.io/google_appengine/java-compat` as a base image.

**Comment by dt-rush** [comment]
The error:

    [INFO] Beginning deployment...
    [INFO] ERROR: (gcloud.preview.app.deploy) There is a Dockerfile in the current directory, and the runtime field in /tmp/1447436161590-0/app.yaml is currently set to [runtime: java7]. To use your Dockerfile to build a custom runtime, set the runtime field in /tmp/1447436161590-0/app.yaml to [runtime: custom]. To continue using the [java7] runtime, please omit the Dockerfile from this directory.
    [ERROR] Error: gcloud app command with exit code : 1
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 11.318s
    [INFO] Finished at: Fri Nov 13 17:36:02 UTC 2015
    [INFO] Final Memory: 15M/56M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal com.google.appengine:gcloud-maven-plugin:2.0.9.72.v20150804:deploy (default-cli) on project mavenHello: Error: gcloud app command exit code is: 1 -> [Help 1]

**Comment by ludoch** [comment]
Please upgrade to plugin version

2.0.9.86.20151113
To see if this is better.
Ludo

**Comment by dt-rush** [comment]
Hey Ludo,

This did indeed seem to fix the issue. I'm now stuck with what appears to be a generalized infrastructural issue with Managed VM deployment, having got past the original issue. It hangs after the following for a long time:

    [INFO] Beginning deployment...
    [INFO] Verifying that Managed VMs are enabled and ready.
    [INFO] 
    [INFO] Provisioning remote build service.
    [INFO] Copying certificates for secure access. You may be prompted to create an SSH keypair.
    [INFO] Building and pushing image for module [mvnhello]
    [INFO] -------------------------------------------------------------------- DOCKER BUILD OUTPUT --------------------------------------------------------------------
    [INFO] Step 0 : FROM beta.gcr.io/google_appengine/java-compat
    [INFO] ---> ed8fbbc37adc
    [INFO] Step 1 : ADD . /app
    [INFO] ---> 0fbb8032d7aa
    [INFO] Removing intermediate container df981aa1d8f7
    [INFO] Successfully built 0fbb8032d7aa
    [INFO] -------------------------------------------------------------------------------------------------------------------------------------------------------------
    [INFO] 
    [INFO] Deleted [https://www.googleapis.com/compute/v1/projects/triple-gem-8/zones/us-central1-f/instances/gae-builder-vm-20151113t202634].

After several minutes of this, it goes on to print the following lines:

    [INFO] ERROR: gcloud crashed (ResponseNotReady): 
    [INFO] 
    [INFO] If you would like to report this issue, please run the following command:
    [INFO]   gcloud feedback
    [ERROR] Error: gcloud app command with exit code : 1
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 11:59.584s
    [INFO] Finished at: Fri Nov 13 20:38:22 UTC 2015
    [INFO] Final Memory: 14M/56M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal com.google.appengine:gcloud-maven-plugin:2.0.9.86.v20151111:deploy (default-cli) on project mavenHello: Error: gcloud app command exit code is: 1 -> [Help 1]

[It seems the `ResponseNotReady` is bubbling up from python's httplib.](https://docs.python.org/2/library/httplib.html#httplib.ResponseNotReady)

It seems as though only somebody who could get into the deployment server / remote build server / some other Google infrastructure could explain and fix this weird error. I'm still unable to deploy a working Managed VM app, even though it appears VMs are provisioned.

**Comment by emetchar** [comment]
Any updates on this issue? I'm encountering the same thing

**Comment by ludoch** [comment]
Which plugin version do you have in the pom.xml?
If it old, upgrade to a newer version 2.0.9.90.v20151210
