### ISSUE TITLE
mvn gcloud:module_delete is not working

### ISSUE THREAD

**Issue by estrellis** [GoogleCloudPlatform/gcloud-maven-plugin#66]
[INFO] Running gcloud app modules...
[INFO] Running python -S /tmp/pkb/google-cloud-sdk/lib/googlecloudsdk/gcloud/gcloud.py --quiet --project=egs-test preview app modules
[INFO] Usage: gcloud preview app modules [optional flags] <command>
[INFO]   command may be         cancel-deployment | delete | download | get-logs | list
[INFO]                          | set-default | set-managed-by | start | stop

This is not a complete gcloud command

**Comment by ludoch** [comment]
Will be fixed in  2.0.9.88.v20151124
