### ISSUE TITLE
Does not work with project_id set by gcloud config

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/gcloud-maven-plugin#7]
When project id is set implicitly via gcloud config, the gcloud-maven-plugin runs the gcloud executable with the flag --project=null, which overrides the implicitly set project-id and prevents deployment.

**Comment by ludoch** [comment]
The latest plugin 0.9.58.v20150503 can now read the gcloud settings and find the possible project name there.

**Comment by karankalra** [comment]
I have been following the steps as given here: https://cloud.google.com/appengine/docs/java/managed-vms/maven

This is the error that I have been getting:
Failed to execute goal com.google.appengine:gcloud-maven-plugin:0.9.58.v20150505:run (default-cli) on project appengine-modules-guestbook: Execution error: java.util.NoSuchElementException

I have also tried using different versions of the gcloud-maven-plugin as given here: http://mirrors.ibiblio.org/maven2/com/google/appengine/gcloud-maven-plugin/, but nothing has helped.

Could you please help me out?

Thanks in advance.
