### ISSUE TITLE
Serving static files with a different URL path

### ISSUE THREAD

**Issue by wmwong** [GoogleCloudPlatform/gcloud-maven-plugin#71]
I'm trying to use AppEngine to serve a static file through a differently named URL path (myfile.json served at /some_file).

For the other supported languages such as Python, this can be configured through app.yaml (https://cloud.google.com/appengine/docs/python/config/appconfig?hl=en#Python_app_yaml_Static_file_handlers):

    handlers:
      - url: /some_file
        static_files: myfile.json
        upload: myfile.json

I can't seem to find an equivalent for appengine-web.xml (https://cloud.google.com/appengine/docs/java/config/appconfig#Java_appengine_web_xml_Static_files_and_resource_files). It can seem to only be configured to serve the file using the filename (myfile.json served at /myfile.json).

Is what I'm trying to do possible with AppEngine and Java?

**Comment by ludoch** [comment]
Does not seem to be a gcloud maven bug.

**Comment by wmwong** [comment]
Isn't gcloud maven responsible for generating app.yaml from appengine-web.xml? Or is gcloud doing that and this should be filed with gcloud?

**Comment by ludoch** [comment]
It is the appcfg.java tooling from gae 1 that we are reusing to only do the
staging phase. Not in Gcloud, not Maven.
Maven is just delegating to Gcloud which is delegating to appcfg staging
phase.

**Comment by wmwong** [comment]
Found a bug about the limitations of handlers in Java:
https://code.google.com/p/googleappengine/issues/detail?id=2070&q=java%20static-files&colspec=ID%20Type%20Component%20Status%20Stars%20Summary%20Language%20Priority%20Owner%20Log

Closing this.
