### ISSUE TITLE
Static files configured in appengine-web.xml give 404 in the development server

### ISSUE THREAD

**Issue by wmwong** [GoogleCloudPlatform/gcloud-maven-plugin#72]
Google Cloud SDK 91.0.1
app-engine-java 1.9.30

I have configured appengine-web.xml to serve static files:

    <static-files>
      <include path="/css/*.css" />
    </static-files>

I run the following commands:
$ mvn clean
$ mvn gcloud:run

However, when trying to visit http://localhost:8080/css/index.css, it gives me a 404 with an error message specifying that no handlers could be found.

"mvn gcloud:run" uses dev_appserver.py to start the development server. The app.yaml given is from target/simple-service-webapp/WEB-INF/app.yaml. Looking into this file, I see that the static root is being set to \_\_static\_\_. However, this directory does not exist in target/simple-service-webapp. However, it does exist in target/appengine-staging. In fact, if I copy the dev_appserver.py command and replace simple-service-webapp with appengine-staging, I can reach /css/index.css.

This seems like a bug and that target/simple-service-webapp should have a __static__ directory.

[simple-service-webapp.zip](https://github.com/GoogleCloudPlatform/gcloud-maven-plugin/files/80383/simple-service-webapp.zip)

**Comment by ludoch** [comment]
I guess you would see the same bug without the maven plugin.
So no fix can be done in this github project.
You can track an internal bug 25198225

**Comment by wmwong** [comment]
Thanks for the internal bug. Closing this.
