### ISSUE TITLE
Google API's failing with network unreachable error

### ISSUE THREAD

**Issue by estrellis** [GoogleCloudPlatform/gcloud-maven-plugin#80]
INFO: HTTP ApiProxy I/O error for logservice.Flush: Network is unreachable

**Comment by ludoch** [comment]
This is for the new environment, not the regular managed vms.
Still critical to fix asap. We did a fix in the internal code, and it is working well for a while. Just need to propagate the change in github.

**Comment by ludoch** [comment]
This bug should have been filed in the managed vm project. No big deal.

**Comment by ludoch** [comment]
Was fixed in the other project
