### ISSUE TITLE
promote attribute ignored since 2.0.9.119.v20160801 (auto promote forced)

### ISSUE THREAD

**Issue by erugeri** [GoogleCloudPlatform/gcloud-maven-plugin#96]
Here's a snippet of our pom.xml

```
<plugin>
	<groupId>com.google.appengine</groupId>
	<artifactId>gcloud-maven-plugin</artifactId>
	<version>2.0.9.119.v20160801</version>
	<configuration>
		<promote>false</promote>
	</configuration>
</plugin>
```

Since 2.0.9.119.v20160801, the promote attribute is ignored and the version is automatically promoted and the previous one stopped.

It works as expected with 2.0.9.118.v20160721 and below.

**Comment by ludoch** [comment]
2.0.9.120.v20160803 has a fix.

**Comment by erugeri** [comment]
Thanks for the quick fix!

**Comment by erugeri** [comment]
FYI, it's not yet available on maven central: http://mvnrepository.com/artifact/com.google.appengine/gcloud-maven-plugin

No problem, I'll wait for it ;)
