### ISSUE TITLE
Please provide an option to use "gcloud beta app deploy" instead of "gcloud app deploy"

### ISSUE THREAD

**Issue by sepehre** [GoogleCloudPlatform/gcloud-maven-plugin#97]
Functionality that is only available in "gcloud beta app" commands should be available to gcloud-maven-plugin users.

**Comment by ludoch** [comment]
We can test via this project: https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/managed_vms/endpoints

**Comment by ludoch** [comment]
Fixed.
